### PR TITLE
Use only BootServices in raw module

### PR DESCRIPTION
**Pull request by Ayush1325**
The functions in raw module only need BootServices to work. So it doesn't make much sense to pass them `SystemTable` since `BootServices` might not be available even if `SystemTable` is valid.

Note: This is a breaking change.

### CODE REVIEW

**Comment by dvdhrm** [comment]
Can you elaborate what your reasoning is?

This looks like you want to make the API explicitly state that boot-services are required, and thus you want the caller to pass the boot-services explicitly. It would certainly make it less likely that someone uses the API with a system-table but exited boot-services.

However, this would also limit the implementation to never use runtime-services, or other elements of the system-table. I am unsure whether I see the benefit of this.

I totally support such efforts in higher-level abstractions. There should certainly be ways to achieve what you are supposedly trying here. However, I am a bit wary whether doing this with the raw tables is the right thing.

**Comment by Ayush1325** [comment]
Well, I would expect the `raw::alloc` and `raw::dealloc` to only use Memory Allocation Services in Boot Services and not touch anything (also not cache pointers or do anything particularly stateful). When creating it initially, I considered it something not to be used directly but instead to implement other allocators. Any functionality that uses other parts of the System Table should be implemented in a higher-level API under `alloc` module.

It might be possible that other parts of the System Table might be needed in a new major version of UEFI spec, but I don't think the current spec has anything that should go inside the `raw::alloc` and `raw::dealloc`. Do you have anything particular in mind which should reside in the `raw` module and use other parts of System Table?

**Comment by dvdhrm** [comment]
> Well, I would expect the `raw::alloc` and `raw::dealloc` to only use Memory Allocation Services in Boot Services and not touch anything (also not cache pointers or do anything particularly stateful). When creating it initially, I considered it something not to be used directly but instead to implement other allocators. Any functionality that uses other parts of the System Table should be implemented in a higher-level API under `alloc` module.

The configuration-tables can contain all kinds of hints about which memory block is used for special operations. I wouldn't be surprised to see allocators requiring access to these. Additionally, the runtime services provide access to timing-APIs, which might be crucial for any kind of hardware allocator.

> It might be possible that other parts of the System Table might be needed in a new major version of UEFI spec, but I don't think the current spec has anything that should go inside the `raw::alloc` and `raw::dealloc`. Do you have anything particular in mind which should reside in the `raw` module and use other parts of System Table?

I am not arguing against the technical correctness of this patch. Yes, the raw-alloc API is highly tied to the boot-services allocators, and it does not allow for any context-object to be retained, so other replacements are highly unlikely. However, I really don't see the benefit of your patch. The SystemTable is the de-factor standard context used for all UEFI operations. It is valid and available in the context where the allocators are used. By using a sub-structure as context, you deviate from the default for no real benefit.

Maybe I am missing something here, but I am not convinced this will be beneficial to the API users. What is the particular reason you want the context object to be restricted?

**Comment by Ayush1325** [comment]
The main reason for this patch was to make it more explicit that boot services must be valid for these functions to work. 

If it is valuable to have a complete system table, then  I suppose we can just add a comment to explain that boot services need to be valid clearly.

**Comment by dvdhrm** [comment]
I would prefer not to do this. As I said before, I think we have no precedence using anything but `SystemTable` as context. Especially the configuration tables are certainly interesting to have around. Stuff like `RT_PROPERTIES_TABLE` is useful for runtime services, and I wouldn't want to exclude the boot-services from similar calls.

Thanks for the discussion and proposal, and sorry for not being able to find an compromise.

**Pull request closed without merging**
